apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-ui
  labels:
    app: health-ui-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: health-ui-app
  template:
    metadata:
      labels:
        app: health-ui-app
    spec:
      containers:
      - name: health-ui-app
        image: fdescolpro/example-health:1.0.1
        ports:
          - containerPort: 8080
            protocol: TCP